llama_api_key: KEY_HERE
attemps: 1
conductor_model: meta-llama/llama-3.1-70b-instruct
frontend_address: 127.0.0.1
frontend_port: 7869
is_many_funcs: true
models_port: 81
models_address: 10.32.2.2
prompt_type: 2
url: BASE_URL_FOR_LLAMA3.1_70b
validation_path: /projects/llm_agents_chemistry/exp3_clean.xlsx



